/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import akka.actor.ActorRef;
import akka.actor.ActorSystem;
import akka.actor.Props;
import ticketmasta.actors.VenueActor;
import ticketmasta.services.ITicketService;
import ticketmasta.services.TicketServiceImpl;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
       ITicketService ticketMasta = TicketServiceImpl.getInstance(30, 70);
        try {
	        	while (true) {
	        		// TODO: process command from input
	        }
        } catch (Exception e) {
        		System.err.println(e.getStackTrace());
        } finally {
        		ticketMasta.shutdown();
        }
    }
}
