/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import ticketmasta.objects.SeatHold;
import ticketmasta.services.ITicketService;
import ticketmasta.services.TicketServiceActorImpl;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ITicketService ticketMasta = TicketServiceActorImpl.getInstance(300, 1000);
        try {
//        		SeatHold sh = ticketMasta.findAndHoldSeats(5, "hehe@gmail.com");
//	        	System.out.println(sh.toString());
//	        	System.out.println(ticketMasta.numSeatsAvailable());
////	        	Thread.sleep(4000);
//	        	System.out.println(ticketMasta.reserveSeats(sh.getId(), "hehe@gmail.com"));
//	        	System.out.println(ticketMasta.numSeatsAvailable());
//	        	Thread.sleep(5000);
//	        	System.out.println(ticketMasta.numSeatsAvailable());
//	        	Thread.sleep(5000);
//	        	System.out.println(ticketMasta.numSeatsAvailable());
//	        	System.out.println(ticketMasta.numSeatsAvailable());
	        	while (true) {
	    			
	        }
        } catch (Exception e) {
        		System.err.println(e.getStackTrace().toString());
        } finally {
        		ticketMasta.shutdown();
        }
    }
}
