/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import ticketmasta.services.ITicketService;
import ticketmasta.services.TicketServiceActorImpl;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ITicketService ticketMasta = TicketServiceActorImpl.getInstance(100, 1000);
        try {
	        	System.out.println(ticketMasta.findAndHoldSeats(5, "hehe@gmail.com").toString());
	        	System.out.println(ticketMasta.numSeatsAvailable());
//	        	while (true) {
//	    		// TODO: process command from input
//	        }
        } catch (Exception e) {
        		System.err.println(e.getStackTrace().toString());
        } finally {
        		ticketMasta.shutdown();
        }
    }
}
